<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC2011112810TVR" name="update a record" tests="1" failures="1" timestamp="19 Mar 2012 08:23:54 GMT" time="155.297" errors="0">
  <testcase name="@AfterMethod logout" time="0.0" classname="org.talend.mdm.cases.record.TestRecord">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at org.talend.mdm.Login.logout(Login.java:87)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod logout -->
  <testcase name="@AfterClass killBroswer" time="0.0" classname="org.talend.mdm.cases.record.TestRecord">
    <skipped/>
  </testcase> <!-- @AfterClass killBroswer -->
  <testcase name="testUpdateRecord" time="147.235" classname="org.talend.mdm.cases.record.TestRecord">
    <failure type="java.lang.AssertionError" message="updateARecord expected:&amp;lt;true&amp;gt; but was:&amp;lt;false&amp;gt;">
      <![CDATA[java.lang.AssertionError: updateARecord expected:<true> but was:<false>
	at org.talend.mdm.modules.Record.updateRecord(Record.java:40)
	at org.talend.mdm.impl.RecordImpl.updateRecordImpl(RecordImpl.java:22)
	at org.talend.mdm.cases.record.TestRecord.testUpdateRecord(TestRecord.java:31)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateRecord -->
</testsuite> <!-- update a record -->
