<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="265692" started-at="2012-07-09T13:36:09Z" finished-at="2012-07-09T13:40:35Z">
    <groups>
    </groups>
    <test name="Commandline_TestCommandline" duration-ms="265692" started-at="2012-07-09T13:36:09Z" finished-at="2012-07-09T13:40:35Z">
      <class name="com.talend.tac.cases.commandline.TestCommandline">
        <test-method status="FAIL" signature="testCommandlineExecuteAllJob(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)" name="testCommandlineExecuteAllJob" duration-ms="265671" started-at="2012-07-09T13:36:09Z" finished-at="2012-07-09T13:40:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ADDED_COMMAND]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://192.168.30.216:8080]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[/org.talend.administrator/]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[proByCommand]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[admin@company.com]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[C:/Program Files (x86)/Java/jdk1.6.0_26/bin/java.exe]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<true> but was:<false>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<true> but was:<false>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:480)
	at org.testng.Assert.assertTrue(Assert.java:37)
	at org.testng.Assert.assertTrue(Assert.java:47)
	at com.talend.tac.cases.commandline.CommandlineImpls.commandlineGetCommandStatusImpl(CommandlineImpls.java:25)
	at com.talend.tac.cases.commandline.CommandlineImpls.commandlineExecuteAllJobImpl(CommandlineImpls.java:505)
	at com.talend.tac.cases.commandline.TestCommandline.testCommandlineExecuteAllJob(TestCommandline.java:292)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:76)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1147)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1039)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1035)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:964)
	at org.testng.TestNG.run(TestNG.java:900)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:110)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
      </class>
    </test>
  </suite>
  <suite name="Suite" duration-ms="0" started-at="2012-07-09T13:40:35Z" finished-at="2012-07-09T13:40:35Z">
    <groups>
    </groups>
  </suite>
</testng-results>
